### ISSUE TITLE
Add a link to the notification email footer to unsubscribe

### ISSUE THREAD

**Issue by jrafanie** [arthurnn/meta#1]
Current email footer:
![image](https://cloud.githubusercontent.com/assets/19339/15398382/6ba8134a-1db1-11e6-975b-785f6534345d.png)

It would be useful to be able to unsubscribe directly from the email.  As an example, here's what bugzilla provides:
![image](https://cloud.githubusercontent.com/assets/19339/15398379/66c0c854-1db1-11e6-8f2b-df367c7cd3a0.png)

**Comment by jrafanie** [comment]
Thanks @arthurnn, fixed!  
![omg_github](https://cloud.githubusercontent.com/assets/19339/15614848/03fdb2b4-2409-11e6-9a39-59ea16def16c.png)

**Comment by arthurnn** [comment]
FWIW it wasnt me =)

**Comment by jrafanie** [comment]
Interesting...
