### ISSUE TITLE
Hide diffs for files in specific folders

### ISSUE THREAD

**Issue by phoet** [arthurnn/meta#14]
It would be really helpful to have some kind of annotation to tell GitHub that it should not show diffs for files in a specific folder. That setting could be on a whole repo, through a config-file or maybe some pull-request tag etc.

That could greatly reduce the clutter of diffs for something like a `vendor` or `gen` folder that don't need to be reviewed.

While the desired behavior could be implemented with a 3rd party application like a chrome-extension, it would not help in terms of performance and communication between humans as everybody would have to have that extension.

/cc @robin-drexler @n1koo

**Comment by phoet** [comment]
discussion on linguist: https://github.com/github/linguist/issues/714
chrome extension: https://github.com/matthewrobertson/Collapse-Diff

from @dcarral

**Comment by lallenlowe** [comment]
For example, we have nock recorded data in our repo for our tests. Every time we have to update the tests, our PR diff gets swamped by those nock json files. We would love to be able to filter out the directory they live in.

**Comment by seeker1983** [comment]
If it's completed, how it can be configured? Cause google leads to this page... would be nice to have syntax example here

**Comment by filipesilva** [comment]
Docs at https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
More details at https://github.com/github-linguist/linguist/blob/main/docs/overrides.md
