### ISSUE TITLE
Prevent every avatar in an organization from loading separately on new issue

### ISSUE THREAD

**Issue by kmcphillips** [arthurnn/meta#20]
@arthurnn @csfrancis

When opening a new issue all avatars are loaded for the user autocomplete. We have nearly 1200 users in our organization. It takes ~20 seconds to become usable.

I use a regex in AdBlock to prevent the avatars from being loaded. It looks like this, every time I create a new issue:

![github_avatars2](https://cloud.githubusercontent.com/assets/84159/17989402/f8c6e7b0-6afa-11e6-8cc3-7921bbe92379.gif)

**Comment by csfrancis** [comment]
❤️ ❤️ ❤️ ❤️

**Comment by bhuga** [comment]
> I use a regex in AdBlock to prevent the avatars from being loaded. It looks like this, every time I create a new issue:

Can you share how you did this?

**Comment by kmcphillips** [comment]
@bhuga Added this rule to AdBlock as a custom rule:

```
||avatars*.githubusercontent.com/u/*?v=3&s=40$image
```

**Comment by bhuga** [comment]
:bow: thanks for the tip!

**Comment by arthurnn** [comment]
I just fixed this and it is deployed in production. 
issues and pr /new should load way faster now, and not affect the autocomplete load.

cheers.

**Comment by csfrancis** [comment]
Yessssssssss @arthurnn - if you were a Shopify employee you'd be getting all of the unicorns right now:

![image](https://cloud.githubusercontent.com/assets/4303686/20123405/d80e9068-a5ec-11e6-8a32-cbece8c8e618.png)

**Comment by arthurnn** [comment]
❤️  💜  💛  💚  💓  😍

**Comment by bhuga** [comment]
![awesome_power_rangers](https://cloud.githubusercontent.com/assets/12676/20127327/08e15458-a603-11e6-918a-4c4ea8893de9.gif)

**Comment by kmcphillips** [comment]
![](http://i.imgur.com/C18lvp4.gif)

**Comment by boourns** [comment]
YESSSSSSSSSSSSSSSS

**Comment by WillsonSmith** [comment]
😍
