### ISSUE TITLE
Allow me to see full list of repositories I contributed to

### ISSUE THREAD

**Issue by summasmiff** [arthurnn/meta#27]
From the right hand sidebar on the homepage, I can see repos I have contributed to. However, this list is not comprehensive, and only lists recent contributions. If I contributed to a repo infrequently or long ago, I don't know how to get back to it from within the Github interface. 

Possible solutions: Add an expanding button to that sidebar similar to the one for your repos ("See 2 more repos..."), or a section on my user page (Perhaps the Repositories page could have a link or a filter?)

@cheshire137

**Comment by cheshire137** [comment]
> Add an expanding button to that sidebar similar to the one for your repos

Since "Your repositories" on the same page behaves with "See X more repositories...", I think this solution makes sense.

**Comment by summasmiff** [comment]
It looks great!!! Thanks guys!!! <3 <3 <3
